---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: intranet-db
  name: intranet-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intranet-db
  template:
    metadata:
      labels:
        app: intranet-db
    spec:
      containers:
        - name: intranet-db
          #image: quay.io/redhattraining/mysql-80:1-251
          image: quay.io/bitnami/mysql:8.0
          envFrom:
            - secretRef:
                name: intranet-db
              prefix: MYSQL_
#          resources:
#            requests:
#              cpu: 10m
#              memory: 256Mi
#            limits:
#              cpu: "1"
#              memory: 512Mi
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -i
                - -c
                - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -i
                - -c
                - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: mysqldb
              mountPath: /var/lib/mysql
#              subPath: data
#          securityContext:
#            capabilities:
#              drop:
#                - ALL
#            allowPrivilegeEscalation: false
#      securityContext:
#        runAsNonRoot: true
#        seccompProfile:
#          type: RuntimeDefault
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: intranet-db
