---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cronjob.yaml

labels:
  - pairs:
      env: development

patches:
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: task-list
      spec:
        tls:
          termination: edge
