apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: myapp-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
      name: myapp-{{name}}
    spec:
      project: default
      destination:
        namespace: myapp
        server: "{{server}}"
      sources:
        - repoURL: https://github.com/soulbrat/rhacm-apps.git
          targetRevision: main
          path: myapp/kustomize/overlays/production
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
